# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9af63f711cbdec92964abaf9e1e7eb0ce868db9f4f689bb16e31cb0357c5bc584b3be1e15b05615f07a713c3e75eddd531b41b409178d265f04f9f7ccf29cba

test:
  secret_key_base: 4afd27e6a56c7898e3b8b8b2210d76a5ade0217fa93cc92d8da122f7012858586ffdc789756872561078ef250123f426553cebc696ba8a2fd2bd7f5703b7e60d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
